ckpt: checkpoints_100_100/tsdiff_cond/traffic_nips/lightning_logs/version_0/checkpoints/last.ckpt
model: conditional
freq: H
context_length: 100
prediction_length: 100
diffusion_config: diffusion_small_config
use_features: False
use_lags: true
init_skip: False
batch_size: 64
scaling_type: mean
device: cuda:0
setup: forecasting
dataset: traffic_nips
num_samples: 100
eval_every: 50
do_final_eval: true
noise_observed: False
normalization: mean